build:
  maxIssues: 0

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: true
    functionThreshold: 12
    constructorThreshold: 12
  CyclomaticComplexMethod:
    threshold: 25
  TooManyFunctions:
    active: false
  LargeClass:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    active: false
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 160
  ReturnCount:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  UnusedPrivateProperty:
    active: true
  WildcardImport:
    active: false
  UnusedImports:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  UnusedParameter:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
